id: A74FDA675
title: A Song of Prayer to Jamyang Loter Wangpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:59:44.534837
  last_modified_at: 2022-02-28 23:59:44.534853
