id: A74FDA675
title: Prayer to Kongtrul Yönten Gyatso
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:59:44.537610
  last_modified_at: 2022-02-28 23:59:44.537613
