id: A74FDA675
title: Regularly Recitable Prayer to the Root Guru, Loter Wangpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:59:44.539901
  last_modified_at: 2022-02-28 23:59:44.539903
