id: A74FDA675
title: Guru Yoga
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:59:44.536416
  last_modified_at: 2022-02-28 23:59:44.536420
