id: A74FDA675
title: 'The Bestowal of Supreme Blessings: Praise to the Vajradhara Loter Wangpo'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:59:44.541430
  last_modified_at: 2022-02-28 23:59:44.541433
